// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnysipzfplmmwgrkjpir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueXNpcHpmcGxtbXdncmtqcGlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1MzkxNTUsImV4cCI6MjA1MTExNTE1NX0.nUfrKr962Bj5qZvodJzZ1IOm9oRdHTMM3sOX4_q5OOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);